"""baseline: full Phase 1 schema (identity, tenancy, academics, people, results)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-08

Why create_all here: this is the *baseline* for a brand-new database — the
schema must match the SQLAlchemy models exactly, so we emit it directly from
``Base.metadata``. Every migration after this one is an explicit, incremental
Alembic revision (never autogenerated drift).

Note on the partial-unique index: ``uq_session_current_school`` (one current
session per school) and the ``uq_component_scope_name`` NULLS NOT DISTINCT
behavior are declared in the models and therefore materialized here.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models  # noqa: F401 — registers every table on Base.metadata
from app.models import Base

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create every table in dependency order (handled by metadata).
    # Indexes (including the partial unique index) are created too.
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)