"""import management: import_batches + import_rows (Phase 3.1 / 3.2)

Revision ID: 0002_import_mgmt
Revises: 0001_baseline
Create Date: 2026-08-10

Legacy data import: an ``import_batches`` row per uploaded file (entity type,
detected columns, source→target column mapping, counters for live progress,
optional parent link for re-imports), plus one ``import_rows`` row per raw
CSV line holding the data verbatim as JSONB alongside per-row validation
errors and user-applied pre-import fixes.

Every column here mirrors ``app.models.imports`` exactly — the project rule is
explicit incremental revisions, never autogenerated drift.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision: str = "0002_import_mgmt"
down_revision: Union[str, None] = "0001_baseline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("school_id", sa.Uuid(), sa.ForeignKey("schools.id", ondelete="CASCADE"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        # status / columns / counters carry Python-side defaults only (models
        # have no server_default) — the metadata must stay diff-clean.
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("columns", JSONB(), nullable=False),
        sa.Column("column_mapping", JSONB(), nullable=True),
        sa.Column("parent_batch_id", sa.Uuid(), sa.ForeignKey("import_batches.id", ondelete="SET NULL"), nullable=True),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("rows_valid", sa.Integer(), nullable=False),
        sa.Column("rows_invalid", sa.Integer(), nullable=False),
        sa.Column("rows_imported", sa.Integer(), nullable=False),
        sa.Column("rows_failed", sa.Integer(), nullable=False),
        sa.Column("error_summary", JSONB(), nullable=False),
        sa.Column("created_by", sa.Uuid(), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Index("ix_import_batches_school_id", "school_id"),
        sa.Index("ix_import_batches_status", "status"),
    )

    op.create_table(
        "import_rows",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("school_id", sa.Uuid(), sa.ForeignKey("schools.id", ondelete="CASCADE"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("batch_id", sa.Uuid(), sa.ForeignKey("import_batches.id", ondelete="CASCADE"), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("data", JSONB(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("errors", JSONB(), nullable=False),
        sa.Column("fixes", JSONB(), nullable=False),
        sa.Column("imported_entity_id", sa.Uuid(), nullable=True),
        sa.Index("ix_import_rows_school_id", "school_id"),
        sa.Index("ix_import_rows_batch_id", "batch_id"),
        sa.Index("ix_import_rows_status", "status"),
    )


def downgrade() -> None:
    op.drop_table("import_rows")
    op.drop_table("import_batches")