"""fees (fee_structures, invoices, payments, student_fee_balances) +
attendance (student_attendance, staff_attendance, attendance_summaries)

Revision ID: 0003_fees_attendance
Revises: 0002_import_mgmt
Create Date: 2026-08-13

The fees + attendance modules (Phase 3 finance + attendance). Every column
here mirrors ``app.models.fees`` and ``app.models.attendance`` exactly — the
project rule is explicit incremental revisions, never autogenerated drift.
Timetables are stateless (derived from the generator), so no tables are
required for the timetable module.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0003_fees_attendance"
down_revision: Union[str, None] = "0002_import_mgmt"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- Fees -----------------------------------------------------------------
    op.create_table(
        "fee_structures",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("school_id", sa.Uuid(), sa.ForeignKey("schools.id", ondelete="CASCADE"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("fee_type", sa.String(length=40), nullable=False),
        sa.Column("amount", sa.Numeric(12, 2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("billing_frequency", sa.String(length=20), nullable=True),
        sa.Column("applicable_to", sa.String(length=40), nullable=True),
        sa.Column("class_level_id", sa.Uuid(), sa.ForeignKey("class_levels.id", ondelete="SET NULL"), nullable=True),
        sa.Column("class_arm_id", sa.Uuid(), sa.ForeignKey("class_arms.id", ondelete="SET NULL"), nullable=True),
        sa.Column("effective_from", sa.String(length=20), nullable=True),
        sa.Column("effective_to", sa.String(length=20), nullable=True),
        sa.Column("is_mandatory", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("allow_override", sa.Boolean(), nullable=True),
        sa.Index("ix_fee_structures_school_id", "school_id"),
    )

    op.create_table(
        "invoices",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("school_id", sa.Uuid(), sa.ForeignKey("schools.id", ondelete="CASCADE"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("student_id", sa.Uuid(), sa.ForeignKey("students.id", ondelete="CASCADE"), nullable=False),
        sa.Column("fee_structure_id", sa.Uuid(), sa.ForeignKey("fee_structures.id", ondelete="SET NULL"), nullable=True),
        sa.Column("term_id", sa.Uuid(), sa.ForeignKey("terms.id", ondelete="SET NULL"), nullable=True),
        sa.Column("session_id", sa.Uuid(), sa.ForeignKey("academic_sessions.id", ondelete="SET NULL"), nullable=True),
        sa.Column("batch_number", sa.String(length=30), nullable=False),
        sa.Column("reference_number", sa.String(length=50), unique=True, nullable=False),
        sa.Column("subtotal", sa.Numeric(12, 2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(12, 2), nullable=True),
        sa.Column("tax_amount", sa.Numeric(12, 2), nullable=True),
        sa.Column("total_amount", sa.Numeric(12, 2), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("issue_date", sa.String(length=10), nullable=True),
        sa.Column("due_date", sa.String(length=10), nullable=True),
        sa.Column("paid_date", sa.String(length=10), nullable=True),
        sa.Column("payment_method", sa.String(length=30), nullable=True),
        sa.Column("transaction_id", sa.String(length=100), nullable=True),
        sa.Column("payment_reference", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Index("ix_invoices_school_id", "school_id"),
        sa.Index("ix_invoices_student_id", "student_id"),
        sa.Index("ix_invoices_fee_structure_id", "fee_structure_id"),
    )

    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("school_id", sa.Uuid(), sa.ForeignKey("schools.id", ondelete="CASCADE"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), sa.ForeignKey("invoices.id", ondelete="CASCADE"), nullable=False),
        sa.Column("student_id", sa.Uuid(), sa.ForeignKey("students.id", ondelete="SET NULL"), nullable=True),
        sa.Column("amount", sa.Numeric(12, 2), nullable=False),
        sa.Column("payment_method", sa.String(length=30), nullable=False),
        sa.Column("payment_reference", sa.String(length=100), nullable=True),
        sa.Column("transaction_id", sa.String(length=100), nullable=True),
        sa.Column("payment_date", sa.String(length=10), nullable=True),
        sa.Column("receipt_number", sa.String(length=50), nullable=True),
        sa.Index("ix_payments_school_id", "school_id"),
        sa.Index("ix_payments_invoice_id", "invoice_id"),
    )

    op.create_table(
        "student_fee_balances",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("school_id", sa.Uuid(), sa.ForeignKey("schools.id", ondelete="CASCADE"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("student_id", sa.Uuid(), sa.ForeignKey("students.id", ondelete="CASCADE"), nullable=False),
        sa.Column("total_owed", sa.Numeric(12, 2), nullable=True),
        sa.Column("total_paid", sa.Numeric(12, 2), nullable=True),
        sa.Column("total_unpaid", sa.Numeric(12, 2), nullable=True),
        sa.Column("current_invoice_id", sa.Uuid(), sa.ForeignKey("invoices.id", ondelete="SET NULL"), nullable=True),
        sa.Column("current_invoice_total", sa.Numeric(12, 2), nullable=True),
        sa.Column("current_invoice_due", sa.String(length=10), nullable=True),
        sa.Column("period_start", sa.String(length=10), nullable=True),
        sa.Column("period_end", sa.String(length=10), nullable=True),
        sa.Column("calculated_at", sa.String(length=10), nullable=True),
        sa.Index("ix_student_fee_balances_school_id", "school_id"),
        sa.Index("ix_student_fee_balances_student_id", "student_id"),
        sa.UniqueConstraint("student_id", "period_start", name="uq_balance_student_period"),
    )

    # --- Attendance ------------------------------------------------------------
    op.create_table(
        "student_attendance",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("school_id", sa.Uuid(), sa.ForeignKey("schools.id", ondelete="CASCADE"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("student_id", sa.Uuid(), sa.ForeignKey("students.id", ondelete="CASCADE"), nullable=False),
        sa.Column("campus_id", sa.Uuid(), sa.ForeignKey("campuses.id", ondelete="SET NULL"), nullable=True),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("marked_by", sa.Uuid(), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Index("ix_student_attendance_school_id", "school_id"),
        sa.Index("ix_student_attendance_student_id", "student_id"),
    )

    op.create_table(
        "staff_attendance",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("school_id", sa.Uuid(), sa.ForeignKey("schools.id", ondelete="CASCADE"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("staff_id", sa.Uuid(), sa.ForeignKey("staff.id", ondelete="CASCADE"), nullable=False),
        sa.Column("campus_id", sa.Uuid(), sa.ForeignKey("campuses.id", ondelete="SET NULL"), nullable=True),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("marked_by", sa.Uuid(), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Index("ix_staff_attendance_school_id", "school_id"),
        sa.Index("ix_staff_attendance_staff_id", "staff_id"),
    )

    op.create_table(
        "attendance_summaries",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("school_id", sa.Uuid(), sa.ForeignKey("schools.id", ondelete="CASCADE"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("student_id", sa.Uuid(), sa.ForeignKey("students.id", ondelete="CASCADE"), nullable=False),
        sa.Column("academic_session_id", sa.Uuid(), sa.ForeignKey("academic_sessions.id", ondelete="CASCADE"), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("total_days", sa.Integer(), nullable=True),
        sa.Column("present_days", sa.Integer(), nullable=True),
        sa.Column("absent_days", sa.Integer(), nullable=True),
        sa.Column("late_days", sa.Integer(), nullable=True),
        sa.Column("excused_days", sa.Integer(), nullable=True),
        sa.Column("percentage", sa.Numeric(5, 2), nullable=True),
        sa.Index("ix_attendance_summaries_school_id", "school_id"),
        sa.Index("ix_attendance_summaries_student_id", "student_id"),
        sa.Index("ix_attendance_summaries_academic_session_id", "academic_session_id"),
        sa.UniqueConstraint("student_id", "academic_session_id", "month", name="uq_attendance_summary"),
    )


def downgrade() -> None:
    op.drop_table("attendance_summaries")
    op.drop_table("staff_attendance")
    op.drop_table("student_attendance")
    op.drop_table("student_fee_balances")
    op.drop_table("payments")
    op.drop_table("invoices")
    op.drop_table("fee_structures")
